export const keys = [
  'Q',
  'W',
  'E',
  'R',
  'T',
  'Y',
  'U',
  'I',
  'O',
  'P',
  'A',
  'S',
  'D',
  'F',
  'G',
  'H',
  'J',
  'K',
  'L',
  'Z',
  'X',
  'C',
  'V',
  'B',
  'N',
  'M',
];

export const keyboardKeys = [
  ['Q', 'greySilver'],
  ['W', 'greySilver'],
  ['E', 'greySilver'],
  ['R', 'greySilver'],
  ['T', 'greySilver'],
  ['Y', 'greySilver'],
  ['U', 'greySilver'],
  ['I', 'greySilver'],
  ['O', 'greySilver'],
  ['P', 'greySilver'],
  ['A', 'greySilver'],
  ['S', 'greySilver'],
  ['D', 'greySilver'],
  ['F', 'greySilver'],
  ['G', 'greySilver'],
  ['H', 'greySilver'],
  ['J', 'greySilver'],
  ['K', 'greySilver'],
  ['L', 'greySilver'],
  ['DEL', 'greySilver'],
  ['Z', 'greySilver'],
  ['X', 'greySilver'],
  ['C', 'greySilver'],
  ['V', 'greySilver'],
  ['B', 'greySilver'],
  ['N', 'greySilver'],
  ['M', 'greySilver'],
  ['ENTER', 'greySilver'],
];
